= Kalender-Projekt

Ein Versuch einer flexiblen grafischen Oberfläche für die Blockplanung der Azubis


== TODOs

* Aktuell ist der Datenfluss zwischen Planner und PlannerEntry unsauber über den PlannerStore realisiert - geht das auch anders?
* Der Planner brauch zum korrekten Anzeigen der nicht geblockten Tage die Informationen aller Blöcke. Diese kommen aber erst durch die PlannerEntry-Items ins Spiel. Eigentlich sollte also der Planner erst nach "korrektem Einlesen aller PlannerEntries" gerendert werden, aber wie lauscht man auf sowas? Aktuell ist ein Dirty-Hack implementiert, der eine boolsche Variable (`render_planner_flag`) im PlannerStorage ändert sobald sich die Blockdaten geändert haben. Der Planner selber wird durch ein template-tag mit v-if gezwungen, bei Änderung an dieser Variablen zu rerendern
* Es Bedarf einiges an Anpassungen und einer Abstrahierungs-Stufe um Spalten (z.B. die zu einer Kalenderwoche) konsistent mit den Daten-Zellen ein- und auszublenden  

== Issues

* Bei Collapsed KW-Headerfields ist die Trennung der Month-Headerfields unschön, dass sollte angepasst werden. Trennung im Bereich der Box der "kollabierten" KW, in der sie auch tatsächlich stattfindet, wäre optimal