= Kalender-Projekt

Ein Versuch einer flexiblen grafischen Oberfläche für die Blockplanung der Azubis

== Kalender-Ansicht
* Es werden alle Tage des gewählten Kalenderjahres angezeit
* Zusätzlich werden alle Randtage des Vor- und oder des Folgejahres angezeigt
die nötig sind, damit der Gesamtzeitraum ausschließlich komplette Kalenderwochen (`KW`, hier: von  Mo-So) enthält
** Beispiel der 01.01.2022 sowie der 31.12.2022 waren jeweils Samstage. Für dieses Jahr würde die Übersich also
über den Bereich des 01.01.2022 bis zum 31.12.2022 außerdem die Bereiche 27.12.2021-31.12.2021 sowie den 01.01.2023 beinhalten (_Padding_)
* Die Ansicht enhält als Header-Zeilen
** zu oberst die Monate mit Namen
*** Zu klären: Wie soll hier auf die zusätzlichen Bereiche (Alt-Dezember-Anteil vor Januar, bzw. Zukunfts-Januar-Anteil nach Dezember)
reagiert werden?
** hierauf folgt die Zeile der Kalenderwochen, die ganz besonders wichtig für die Übersichtlichkeit ist - deswegen wird auch gerade hier auf eine einheitliche
Länge über den gesamten Bereich gelegt:
*** mit Namen angezeigt werden die KWs 1 bis 52. Die übrigen werden *ohne* Namen angezeigt
*** die erste KW ist immer die, *in der der 4. Januar* liegt*.
*** Kalenderwochen lassen sich per Klick auf ihr Feld in der KW-Kopfzeile *ein- und ausklappen*, so dass Kompromiss aus Detail und Übersicht bedarfsgerecht über den gesamten
Bereich individuell und sehr intuitiv steuerbar entsteht
*** ausgeklappte KWs stellen visuell einer Untertabelle dar, die als letzte Kopfzeile die Tage der Woche (Mo-So) als Spalten enthält. Direkt darunter beginnen dann auch die Datenzeilen des Kalenders
*** eine eingeklappte, hier häufig auch als _kollabierte_ KW bezeichnete Kalenderwoche reduziert sich visuell auch eine Spalte. Die Zeilen unter ihr können die Daten nicht mehr sauber auf einzelne Tage aufgelöst darstellen, versuchen dies aber qualitativ anzunähern - d.h., Tabellendaten, die unterwöchig beginnen oder Enden haben einen sichtbaren Übergang innerhalb dieser reduzierten Datenzellen



== TODOs
* TableInteractionService wird immer unübersichtlicher. Patterns anwenden um States und State-Transisions besser zu verwalten!
* PlannerEntry ablösen: Planner ist einziger View, DatenIO über events
* Interaktivität:
** Hinzufügen eines Blocks
*** Ein links-Klick auf eine freie Zelle startet den Vorgang. Ab hier wird bei jeder Bewegung des auf ein freies Feld wird der eingeschlossene rechteckige Bereicht von Start-Feld zum Ist-Feld eingefärbt/eingerahmt o.Ä. - sofern alle eingeschlossenen Felder frei sind. Ist mindestens eines der Felder nicht frei, so erfolgt eine andere Art der Markierung.
*** Ein Rechts-Klick bricht den Vorgang ab.
*** Ein zweiter Links-Klick fügt den Bereich hinzu, sofern er komplett frei ist (weitere, schärfere Markierung beim zweiten Linksklick, falls mindestens ein Feld nicht frei ist, die darauf hinweist, dass die Auswahl nicht zulässig ist).
*** Auf das Hinzufügen folgt direkt ein modaler Dialog, in dem die Bezeichnung und die Farbe bestimmt werden (ob direkt oder über eine Auswahlbox/Kategorie ist noch zu klären). Auch kann in diesem Schritt nochmals abgebrochen werden (Button), mit dem gleichen Ergebnis wie beim vorzeitigen Rechtsklick (s.o.)
*** ACHTUNG: Selbst das Hinzufügen ändert noch nichts an den Daten im "Backend". Sämtliche Änderungen am Frontend können selbst über mehrere Schritte zurückgerollt werden und müssen, bei Bedarf, explizit aus Auftrag gesendet werden, wenn sie persistiert werden sollen (Analog zu beispielsweise einem Partitionsmanager)
** Ändern (und ggf. Entfernen) eines Blocks
*** Ein Klick auf einen Betriebs- oder Urlaubsblocks (Schul- und/oder Ferienblöcke sind nicht änderbar) markiert diesen sichtbar (Umrandung/Schatten o.Ä.) und lässt ihn "manipulieren"
*** Entweder poppt (analog zu dem Hinzufügen oben nach dem zweiten Klick) ein modaler Dialog auf, der eine Anpassung der Farbe und/oder der Bezeichnung des Blockes (wie zuvor ist auch hier noch zu klären ob dies über eine Auswahlbox/Katorien oder gar direkt erfolgen können soll) ermöglicht wird, oder es gibt wird ein Mini-Menü an/neben dem Block eingeblendet, dass diese Änderungen über entsprechende Icons und/oder direkte Manipulation des Textes (muss dann natürlich wieder selektierbar sein) ermöglicht. In letzterem Fall, der auf Dauer sicher angenehmer wäre, könnte auch die Möglichkeit zum Verschieben und dem Ändern der Größe (analog zu z.B. Powerpoint) gegeben werden. Mehr Aufwand aber auch deutlicher Mehrwert.
*** Das Entfernen eines markierten Blockes könnte im zweiten Fall einfach auch durch ein Icon und die delete-Taste intuitiv ermöglicht werden. Im ersten Fall wäre ein entsprechender Button in den modalen Dialog aufzunehmen
*** Sämtliche Änderungen sollten bis zu einem gewissen Punkt rückgängig gemacht werden können (str-z, str-y), das ist natürlich eine Herausforderung :-)
*** Auch hier gilt natürlich, dass erst beim expliziten Absenden des Persistierungs-Auftrags die Änderungen aus der Session in das System übernommen werden


== Issues

